// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn0skpKO11mI8_L46wMJuITfPPfP7lfZE',
    appId: '1:632058709841:web:dd9558460a974e9ba97570',
    messagingSenderId: '632058709841',
    projectId: 'motodigo-30874',
    authDomain: 'motodigo-30874.firebaseapp.com',
    storageBucket: 'motodigo-30874.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLdp8Jdiv-Ci9PE8uCGmbbuL2x4LcqbXk',
    appId: '1:632058709841:android:dc0d875e5140002fa97570',
    messagingSenderId: '632058709841',
    projectId: 'motodigo-30874',
    storageBucket: 'motodigo-30874.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjzJrwX0FdjflLbyRIrM40f22J09zKqbs',
    appId: '1:632058709841:ios:76d84502158b8b39a97570',
    messagingSenderId: '632058709841',
    projectId: 'motodigo-30874',
    storageBucket: 'motodigo-30874.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjzJrwX0FdjflLbyRIrM40f22J09zKqbs',
    appId: '1:632058709841:ios:76d84502158b8b39a97570',
    messagingSenderId: '632058709841',
    projectId: 'motodigo-30874',
    storageBucket: 'motodigo-30874.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn0skpKO11mI8_L46wMJuITfPPfP7lfZE',
    appId: '1:632058709841:web:8b33e0ea17ce8ff7a97570',
    messagingSenderId: '632058709841',
    projectId: 'motodigo-30874',
    authDomain: 'motodigo-30874.firebaseapp.com',
    storageBucket: 'motodigo-30874.firebasestorage.app',
  );
}
