name: Pipeline Securite MotoDigo

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  verification-securite:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verification des Secrets (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Verification du Code (Semgrep)
        run: |
          pip install semgrep
          semgrep scan --config auto --error